[package]
name = "pixelflut-rs"
version = "0.2.0"
authors = ["Marco 'don' Kaulea <don@0xbeef.org>"]

[dependencies]
rand = "0.3.0"
image = "0.10.0"
piston = "0.26.0"
piston2d-graphics = "0.18.0"
pistoncore-glutin_window = "0.31.0"
piston2d-opengl_graphics = "0.35.0"
byteorder = "*"
